name: PRO Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Checkout deploy repo
      uses: actions/checkout@v2
      with:
        repository: miguelFLG13/Cloud-Deploy
        path: deploy
    - name: Checkout wabe-domain
      uses: actions/checkout@v2
      with:
        repository: wealthabout/wabe-domain
        token: ${{ secrets.PAT }}
        path: domain
    - name: Prepare deploy with python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install deploy dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deploy/requirements.pip
    - name: Deploying
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        REGION_NAME: ${{ secrets.REGION_NAME }}
        BUCKET_PRO: ${{ secrets.BUCKET_PRO }}
      run: |
        cd deploy
        python deploy_backend.py PRO
