name: PRO Create Layers

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  create:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Checkout deploy repo
      uses: actions/checkout@v2
      with:
        repository: miguelFLG13/Cloud-Deploy
        path: deploy
    - name: Checkout wabe-domain
      uses: actions/checkout@v2
      with:
        repository: wealthabout/wabe-domain
        token: ${{ secrets.PAT }}
        path: domain
    - name: Prepare with python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install create layers dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deploy/requirements.pip
    - name: Prepare dependencies
      run: |
        python -m pip install --upgrade pip
        mkdir -p layer/python/lib/python3.8/site-packages
        cd layer
        pip install -r ../requirements.pip --target python/lib/python3.8/site-packages
        pip install -r ../domain/requirements.pip --target python/lib/python3.8/site-packages
        cp -r ../_custom_packages/* python/lib/python3.8/site-packages
        zip -r ../layer.zip ./*
    - name: Creating Layer
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        REGION_NAME: ${{ secrets.REGION_NAME }}
        BUCKET_PRO: ${{ secrets.BUCKET_PRO }}
        LAYER_NAME: ${{ secrets.LAYER_NAME }}
      run: |
        cd deploy
        python create_serverless_layers.py PRO layer.zip
